server:
  port: 8080

spring:
  datasource:
    url: ${PROTO_DB_URL:jdbc:postgresql://localhost:5432/protobuilder}
    username: ${PROTO_DB_USER:protouser}
    password: ${PROTO_DB_PASS:protopass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info


