server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protobuilder
    username: protobuilder
    password: protobuilder
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info


